[package]
name = "paragon"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
dashmap = "6.1.0"
futures = "0.3.31"
once_cell = "1.21.3"
polars = { version = "0.48.1", features = ["parquet", "timezones"] }
tokio = {version = "1.45.1" , features = ["full"] }
